examen/urls.py
from django.urls import path
from .views import CreateExamenView, DetalleExamen, ExamenListView, PlanesView, HomeUserView
app_name='examen'

urlpatterns=[
    # path('',inicio, name='inicio'),
    # path('',HomeView.as_view(), name='inicio'),
    path('usuario/',HomeUserView.as_view(), name='home-user'),
    path('examenes/',ExamenListView.as_view(), name='examenes'),
    path('detalle-examen/<pk>/',DetalleExamen.as_view(), name='detalle-examen'),
    # path('examen/<exam_pk>/',realizarExamen, name='create-examen'),
    path('examen/<pk>/',CreateExamenView.as_view(), name='realizar-examen'),
    path('planes/',PlanesView.as_view(), name=''),
]

perfil/urls.py
from django.urls import path
from .views import ConfirmarPagoView, DetallePerfilView, DetallesPagoView, EditarPerfilView, GraciasView, ListaPagosView, PlanesView,HomeView, affiliateApplication, initPerfil, pagarPlan, referedCode
app_name='perfil'

urlpatterns=[
    path('',HomeView.as_view(), name='home'),
    path('init/',initPerfil, name='init'),
    path('planes/',PlanesView.as_view(), name='planes'),
    path('editar-perfil/<pk>/',EditarPerfilView.as_view(), name='editar-perfil'),
    path('detalle-perfil/<pk>/',DetallePerfilView.as_view(), name='detalle-perfil'),

    path('planes/pagar/',pagarPlan, name='pagar'),
    path('gracias/',GraciasView.as_view(), name='gracias'),
    path('confirmar-pago/',ConfirmarPagoView.as_view(), name='confirmar-pago'),
    path('lista-pagos/<pk>/',ListaPagosView.as_view(), name='lista-pagos'),
    path('detalles-pago/<pk>/',DetallesPagoView.as_view(), name='detalles-pago'),

    path('solicitar-afiliado/', affiliateApplication, name='solicitar-afiliado'),
    path('ref-code/<str:ref_code>/', referedCode, name='ref-code'), #Enviar en la solicitud el codigo de usuario y la url a la que sera redirigido

]

wexamen/urls.py
from django.contrib import admin
from django.urls import path, include
from affiliate.views import redirect_url_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perfil.urls', namespace='perfil')),
    path('examen/', include('examen.urls', namespace='examen')),
    path('accounts/', include('allauth.urls')),
    path('affiliate/', include('affiliate.urls')),

    path('u/<str:shortened_part>', redirect_url_view, name='redirect-url-short'),

    path('__debug__/', include('debug_toolbar.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html
  lang="en"
  class="light-style customizer-hide"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="{% static '/assets/' %}"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>WEXAMEN | {% block title %}{% endblock title %}</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
   
    <link rel="stylesheet" href="{% static '/assets/vendor/fonts/boxicons.css' %}" />

    <!-- Core CSS -->
  
    <link rel="stylesheet" href="{% static '/assets/vendor/css/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static '/assets/vendor/css/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static '/assets/css/demo.css' %}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static '/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />
 

    <!-- Page CSS -->
    <!-- Page -->
    <link rel="stylesheet" href="{% static '/assets/vendor/css/pages/page-auth.css' %}" />
   
    <!-- Helpers -->
    <script src="{% static '/assets/vendor/js/helpers.js' %}"></script>
   

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static '/assets/js/config.js' %}"></script>
    
  </head>

  <body>
  <body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Menu -->
        {% include "parts/menu.html" %}        
        <!-- / Menu -->

        <!-- Layout container -->
        <div class="layout-page">
          <!-- Navbar -->
          {% include "parts/nav_bar.html" %}
          <!-- / Navbar -->

          <!-- Content wrapper -->
        {% comment %} BLOQUE ALERT {% endcomment %}
            {% if messages %}
        
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <strong>{{ message }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>

                {% endfor %}
          
            {% endif %}
        {% comment %} FIN BLOQUE ALERT {% endcomment %}
          <div class="content-wrapper">
            <!-- Content -->

            {% block content %}
            
            {% endblock content %}
            <!-- / Content -->

            <!-- Footer -->
            {% include "parts/footer.html" %}
            <!-- / Footer -->

            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
      </div>

      <!-- Overlay -->
      <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->


    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    
    <script src="{% static '/assets/vendor/libs/jquery/jquery.js' %}"></script>

    <script src="{% static '/assets/vendor/libs/popper/popper.js' %}"></script>

    <script src="{% static '/assets/vendor/js/bootstrap.js' %}"></script>
 
    <script src="{% static '/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
  

    <script src="{% static '/assets/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->
    <script src="{% static '/assets/js/main.js' %}"></script>


    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>

templates/examen_list.html
{% extends "base.html" %}
{% block title %}
Examenes de tránsito
{% endblock title %}
{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Exámenes /</span> Tránsito</h4>
    <div class="card mb-4">
        <h5 class="card-header">Lista de exámenes para tránsito</h5>
    <div class="card-body">
    <div class="row">




    



<div class="nav-align-top mb-4">
                    <ul class="nav nav-tabs nav-fill" role="tablist">
                      <li class="nav-item">
                        <button
                          type="button"
                          class="nav-link active"
                          role="tab"
                          data-bs-toggle="tab"
                          data-bs-target="#navs-justified-home"
                          aria-controls="navs-justified-home"
                          aria-selected="true"
                        >
                          <i class="tf-icons bx bx-home"></i>Todos los exámenes
                          <span class="badge rounded-pill badge-center h-px-20 w-px-20 bg-label-primary">{{object_list.count}}</span>
                        </button>
                      </li>
                      <li class="nav-item">
                        <button
                          type="button"
                          class="nav-link"
                          role="tab"
                          data-bs-toggle="tab"
                          data-bs-target="#navs-justified-profile"
                          aria-controls="navs-justified-profile"
                          aria-selected="false"
                        >
                          <i class="tf-icons bx bx-user"></i> Examenes realizados
                          <span class="badge rounded-pill badge-center h-px-20 w-px-20 bg-label-primary">{{examenes_realizados.count}}</span>

                        </button>
                      </li>
                     
                    </ul>
                    <div class="tab-content">
                      <div class="tab-pane fade show active" id="navs-justified-home" role="tabpanel">

                            <div class="demo-inline-spacing mt-3">
                            <ul class="list-group">


              <div class="card">
           
                <div class="table-responsive text-nowrap">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Examen</th>
                        <th>Categoría</th>
                        <th>Total de preguntas</th>
                        <th>Creditos</th>

                        
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                    {% for obj in object_list %}
                      <tr>
                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{forloop.counter}}</strong></td>
                        <td><a href="{% url 'examen:realizar-examen' obj.pk %}">Examen - {{obj.pk}}</a></td>
                        {% if obj.categoria %}
                          <td>{{obj.categoria}}</td>
                        {% else %}
                          <td>Sin categoría</td>
                        {% endif %}
                        <td>{{obj.preguntas.count}}</td>
                        <td><span class="badge bg-success">{{obj.costo}}</span></td>
                        
                      </tr>
                    {% endfor %}
                      
                      
                      
                    </tbody>
                  </table>
                </div>
            </div>

                        
                                {% comment %} <span class="badge bg-success">2</span>
                                <span class="badge bg-danger rounded-pill">3</span> {% endcomment %}
                            </ul>
                            </div>
                 



                      </div>
                      <div class="tab-pane fade" id="navs-justified-profile" role="tabpanel">
                        




                        <div class="card">
           
                <div class="table-responsive text-nowrap">
                  <table class="table">
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Examen</th>
                        <th>Categoría</th>
                        <th>Fecha</th>
                        <th>Total de preguntas</th>
                        <th>Creditos</th>
                        <th>Resultado</th>
                        
                      </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                   {% for examen in examenes_realizados|dictsortreversed:"created_at" %}
                      <tr>
                        <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{forloop.counter}}</strong></td>
                        {% comment %} <td><a href="{% url 'examen:realizar-examen' examen.pk %}">Examen - {{examen.pk}}</a></td> {% endcomment %}
                        {% comment %} Aqui va un enlace al detalle del examen realido {% endcomment %}
                        <td><a href="{% url 'examen:detalle-examen' examen.pk %}">Examen - {{examen.pk}}</a></td>
                        {% if examen.categoria %}
                          <td>{{examen.categoria}}</td>
                        {% else %}
                          <td>Sin categoría</td>
                        {% endif %}
                        
                        <td>{{examen.created_at}}</td>

                        <td>{{examen.preguntas_respondidas.count}}</td>
                        <td>{{examen.costo}}</td>
                        <td><span class="badge bg-primary">{{examen.resultado}} pts</span></td>
                        
                      </tr>
                    {% endfor %} 
                      
                      
                      
                    </tbody>
                  </table>
                </div>
            </div>





                      </div>
                 
                    </div>
                  </div>



    </div>
    </div>
    </div>
</div>

{% endblock content %}

templates/gracias.html
{% extends "base.html" %}
{% block title %}
Gracias
{% endblock title %}
{% block content %}

<div class="container-xxl flex-grow-1 container-p-y">
{% comment %} <h4 class="fw-bold py-3 mb-4"></h4> {% endcomment %}
<div class="card mb-4">


<div class="card-body">
<div class="row">
<div class="col-xl-12">
    


  <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Muchas gracias!!!</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <button class="btn btn-primary btn-lg" type="button">Example button</button>
      </div>
    </div>



</div>
</div>
</div>
</div>
</div>


{% endblock content %}

templates/planes.html
{% extends "base.html" %}
{% load examen_extras %}
{% block title %}
Examen
{% endblock title %}
{% block content %}





<div class="container-xxl flex-grow-1 container-p-y">
<h4 class="fw-bold py-3 mb-4">Planes</h4>
<div class="card mb-4">


<div class="card-body">
<div class="row">
<div class="col-xl-12">
    
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal">Pricing</h1>
      <p class="fs-5 text-muted">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
    </div>











    <main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Básico</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$10<small class="text-muted fw-light">/cup</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              {% comment %} <li>10 cup de credito para exámenes</li> {% endcomment %}
              <li>10 cup de credito para exámenes</li>
              {% comment %} <li>2 GB of storage</li>
              <li>Email support</li>
              <li>Help center access</li> {% endcomment %}
            </ul>
            <form action="{%url 'perfil:pagar'%}" method="POST">
            {% csrf_token %}
                <input type="hidden" name="title" value="Titulo del pla">
                <input type="hidden" name="description" value="Descripcion del plan">
                <input type="hidden" name="price" value="1.00">
                <input type="hidden" name="plan_type" value="BASICO">
                <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Comprar</button>
            </form>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Medio</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$25<small class="text-muted fw-light">/cup</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>25 cup de credito para exámenes</li>
              <li>Acceso a documentación para estudio</li>
            

              {% comment %} <li>10 GB of storage</li>
              <li>Priority email support</li>
              <li>Help center access</li> {% endcomment %}
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Comenzar</button>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
          <div class="card-header py-3 text-white bg-primary border-primary">
            <h4 class="my-0 fw-normal" style="color: aliceblue;">Pro</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">$75<small class="text-muted fw-light">/cup</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>Credito Ilimitado para exámenes por un mes</li>
              <li>Acceso Ilimitado a documentación para estudio por un mes</li>
              {% comment %} <li>30 users included</li>
              <li>15 GB of storage</li> {% endcomment %}
              <li>75 cup de credito para descargas</li>
           
              {% comment %} <li>Help center access</li> {% endcomment %}
            </ul>
            <button type="button" class="w-100 btn btn-lg btn-primary">Comenzar</button>
          </div>
        </div>
      </div>
    </div>

    {% comment %} <h2 class="display-6 text-center mb-4">Compare plans</h2> {% endcomment %}

    {% comment %} <div class="table-responsive">
      <table class="table text-center">
        <thead>
          <tr>
            <th style="width: 34%;"></th>
            <th style="width: 22%;">Free</th>
            <th style="width: 22%;">Pro</th>
            <th style="width: 22%;">Enterprise</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" class="text-start">Public</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Private</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>

        <tbody>
          <tr>
            <th scope="row" class="text-start">Permissions</th>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Sharing</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Unlimited members</th>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
          <tr>
            <th scope="row" class="text-start">Extra security</th>
            <td></td>
            <td></td>
            <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
          </tr>
        </tbody>
      </table>
    </div> {% endcomment %}
  </main>











</div>
</div>
</div>
</div>
</div>



{% endblock content %}