affiliate/urls.py
from django.urls import path, re_path

from . import views

app_name='affiliate'
urlpatterns = [
    # path('links/', views.affiliateLinks, name='links'),
    path('links/', views.AffiliateLinks.as_view(), name='links'),
    path('shortener/', views.shortener, name='shortener'),
	# re_path(r"^shortener/(?P<long_url>[a-zA-Z0-9_-]+)/$", views.shortener, name="shortener",),


]

examen/urls.py
from django.urls import path
from .views import CreateExamenView, DetalleExamen, ExamenListView, PlanesView, HomeUserView
app_name='examen'

urlpatterns=[
    # path('',inicio, name='inicio'),
    # path('',HomeView.as_view(), name='inicio'),
    path('usuario/',HomeUserView.as_view(), name='home-user'),
    path('examenes/',ExamenListView.as_view(), name='examenes'),
    path('detalle-examen/<pk>/',DetalleExamen.as_view(), name='detalle-examen'),
    # path('examen/<exam_pk>/',realizarExamen, name='create-examen'),
    path('examen/<pk>/',CreateExamenView.as_view(), name='realizar-examen'),
    path('planes/',PlanesView.as_view(), name=''),
]

perfil/urls.py
from django.urls import path
from .views import ConfirmarPagoView, DetallePerfilView, DetallesPagoView, EditarPerfilView, GraciasView, ListaPagosView, PlanesView,HomeView, affiliateApplication, initPerfil, pagarPlan, referedCode
app_name='perfil'

urlpatterns=[
    path('',HomeView.as_view(), name='home'),
    path('init/',initPerfil, name='init'),
    path('planes/',PlanesView.as_view(), name='planes'),
    path('editar-perfil/<pk>/',EditarPerfilView.as_view(), name='editar-perfil'),
    path('detalle-perfil/<pk>/',DetallePerfilView.as_view(), name='detalle-perfil'),

    path('planes/pagar/',pagarPlan, name='pagar'),
    path('gracias/',GraciasView.as_view(), name='gracias'),
    path('confirmar-pago/',ConfirmarPagoView.as_view(), name='confirmar-pago'),
    path('lista-pagos/<pk>/',ListaPagosView.as_view(), name='lista-pagos'),
    path('detalles-pago/<pk>/',DetallesPagoView.as_view(), name='detalles-pago'),

    path('solicitar-afiliado/', affiliateApplication, name='solicitar-afiliado'),
    path('ref-code/<str:ref_code>/', referedCode, name='ref-code'), #Enviar en la solicitud el codigo de usuario y la url a la que sera redirigido

]

wexamen/urls.py
from django.contrib import admin
from django.urls import path, include
from affiliate.views import redirect_url_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('perfil.urls', namespace='perfil')),
    path('examen/', include('examen.urls', namespace='examen')),
    path('accounts/', include('allauth.urls')),
    path('affiliate/', include('affiliate.urls')),

    path('u/<str:shortened_part>', redirect_url_view, name='redirect-url-short'),

    path('__debug__/', include('debug_toolbar.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perfil/models.py
from django.urls import reverse
import os
from django.db import models
from affiliate.models import Shortener
from perfil.utils import generate_ref_code
from django.db.models.signals import post_save
# from examen.models import PreguntasRespondidas
from django.conf import settings
from django.contrib.auth.models import User
from PIL import Image

from django_resized import ResizedImageField




def user_directory_path_profile(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    profile_pic_name = 'user_{0}/profile.jpg'.format(instance.usuario.id)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_pic_name)

    if os.path.exists(full_path):
    	os.remove(full_path)

    return profile_pic_name

def user_directory_path_banner(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    banner_pic_name = 'user_{0}/banner.jpg'.format(instance.usuario.id)
    full_path = os.path.join(settings.MEDIA_ROOT, banner_pic_name)

    if os.path.exists(full_path):
    	os.remove(full_path)

#Posiblemente a cambiar por  profile_pic_name
    return banner_pic_name 









class Profile(models.Model): #QuizUser
    GENDER_CHOICE = (
				('HOMBRE', 'HOMBRE'),
				('MUJER', 'MUJER'),
				('OTRO', 'OTRO'),

    )
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(verbose_name="Nombres", max_length=25, blank=True, null=True)
    last_name = models.CharField(verbose_name="Apellidos", max_length=25, blank=True, null=True)
    puntaje_total=models.DecimalField(verbose_name="Puntaje total", default=0, decimal_places=2, max_digits=6)
    presupuesto=models.DecimalField(verbose_name="Presupuesto", default=0, decimal_places=2, max_digits=6)
   
    url = models.CharField(max_length=80, null=True, blank=True)
    profile_info = models.TextField(max_length=150, null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    
    phone = models.CharField(max_length=11, blank=True, null=True)
    ci = models.CharField(max_length=11, blank=True, null=True)
    code = models.CharField(max_length=20, blank=True, unique=True)
    recommended_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="recommended")
    updated = models.DateTimeField(auto_now=True)
	# created = models.DateTimeField(auto_now_add=True)
    gender = models.CharField(max_length=6, choices=GENDER_CHOICE, blank=True, null=True)
    affiliated=models.BooleanField(default=False, blank=True, null=True)#Solo se aprueba desde el administrador cuando cumpla los requisitos verificables
    affiliated_url=models.CharField(max_length=30, blank=True, null=True)#Segenera cuando sea aprovada la solicitud de afiliado
    recommended_plan=models.ManyToManyField('Plan', blank=True)
    
	# favorites = models.ManyToManyField(Post)
    picture = ResizedImageField(size=[300, 300], quality=90, upload_to=user_directory_path_profile)
    # picture = models.ImageField(upload_to=user_directory_path_profile, blank=True, null=True, verbose_name='Picture')
    banner = models.ImageField(upload_to=user_directory_path_banner, blank=True, null=True, verbose_name='Banner')

	# def save(self, *args, **kwargs):
	# 	super().save(*args, **kwargs)
	# 	SIZE = 250, 250

	# 	if self.picture:
	# 		pic = Image.open(self.picture.path)
	# 		pic.thumbnail(SIZE, Image.LANCZOS)
	# 		pic.save(self.picture.path)

    def __str__(self):
	    return f"{self.usuario.username} - {self.code}"

    def get_recommended_profiles(self):
	    pass
    
    def get_absolute_url(self):
        return reverse("perfil:detalle-perfil", kwargs={'pk': self.pk})
        
    def save(self, *args, **kwargs):
        # SIZE = 250, 250
        if self.code=="":
            code = generate_ref_code()
            self.code = code

        # if self.picture:
        #     pic = Image.open(self.picture.path)
        #     pic.thumbnail(SIZE, Image.LANCZOS)
        #     pic.save(self.picture.path)
        super().save(*args, **kwargs)
        

def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(usuario=instance)

def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


class Plan(models.Model):
    TYPE_PLAN_CHICES={
        ('BASICO','BASICO'),
        ('MEDIO','MEDIO'),
        ('PRO','PRO'),
    }
    plan_type=models.CharField(max_length=25, choices=TYPE_PLAN_CHICES)
    title = models.CharField(max_length=25)
    caracteristica1 = models.CharField(max_length=50, blank=True, null=True)
    caracteristica2 = models.CharField(max_length=50, blank=True, null=True)
    caracteristica3 = models.CharField(max_length=50, blank=True, null=True)
    caracteristica4 = models.CharField(max_length=50, blank=True, null=True)
    caracteristica5 = models.CharField(max_length=50, blank=True, null=True)
    description=models.TextField()
    price=models.DecimalField(verbose_name="Precio", max_digits=6, default=0, decimal_places=2)
    credit = models.DecimalField(verbose_name="Creditos del plan", max_digits=6, default=0, decimal_places=2)


    def __str__(self):
        return self.title


class PlanPago(models.Model):
    TYPE_PLAN_CHICES={
        ('BASICO','BASICO'),
        ('MEDIO','MEDIO'),
        ('PRO','PRO'),
    }
    plan_type=models.CharField(max_length=25, choices=TYPE_PLAN_CHICES)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    purchused=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(verbose_name="Cantidad pagada", max_digits=6, default=0, decimal_places=2)
    credit = models.DecimalField(verbose_name="Credito adquirido", max_digits=6, default=0, decimal_places=2)
    
    # info de enzona
   
    transaction_uuid=models.CharField(max_length=35)
    user_uuid=models.CharField(max_length=35)
    

    def __str__(self):
        return self.profile.usuario.username




class AffiliateApplication(models.Model):
	profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	aprovated = models.BooleanField(default=False)


	def __str__(self):
		return self.profile.usuario.email
	

def post_save_affiliate_application_riceiver(sender, instance, created, **kwargs):
	shorttener = Shortener.objects.create(user=instance.profile.usuario, long_url=f'ref-code/{instance.profile.code}/?next_url=/')
	
	profile =  Profile.objects.filter(usuario=instance.profile.usuario).update(affiliated=instance.aprovated, affiliated_url=shorttener.short_url)
	

post_save.connect(post_save_affiliate_application_riceiver, sender=AffiliateApplication)

templates/parts/footer.html
<footer class="content-footer footer bg-footer-theme">
              <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                <div class="mb-2 mb-md-0">
                  ©
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  , Hecho con ❤️ by
                  <a href="#" target="_blank" class="footer-link fw-bolder">WEXAMEN</a>
                </div>
                <div>
                  <a href="#" class="footer-link me-4" target="_blank">License</a>
                  <a href="#" target="_blank" class="footer-link me-4">More Themes</a>

                  <a
                    href="#"
                    target="_blank"
                    class="footer-link me-4"
                    >Documentation</a
                  >

                  <a
                    href="#"
                    target="_blank"
                    class="footer-link me-4"
                    >Support</a
                  >
                </div>
              </div>
            </footer>

templates/parts/menu.html
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
          <div class="app-brand demo">
            <a href="index.html" class="app-brand-link">
              <span class="app-brand-logo demo">
                <svg
                  width="25"
                  viewBox="0 0 25 42"
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  xmlns:xlink="http://www.w3.org/1999/xlink"
                >
                  <defs>
                    <path
                      d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                      id="path-1"
                    ></path>
                    <path
                      d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                      id="path-3"
                    ></path>
                    <path
                      d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                      id="path-4"
                    ></path>
                    <path
                      d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                      id="path-5"
                    ></path>
                  </defs>
                  <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                    <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                      <g id="Icon" transform="translate(27.000000, 15.000000)">
                        <g id="Mask" transform="translate(0.000000, 8.000000)">
                          <mask id="mask-2" fill="white">
                            <use xlink:href="#path-1"></use>
                          </mask>
                          <use fill="#696cff" xlink:href="#path-1"></use>
                          <g id="Path-3" mask="url(#mask-2)">
                            <use fill="#696cff" xlink:href="#path-3"></use>
                            <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                          </g>
                          <g id="Path-4" mask="url(#mask-2)">
                            <use fill="#696cff" xlink:href="#path-4"></use>
                            <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                          </g>
                        </g>
                        <g
                          id="Triangle"
                          transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) "
                        >
                          <use fill="#696cff" xlink:href="#path-5"></use>
                          <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                        </g>
                      </g>
                    </g>
                  </g>
                </svg>
              </span>
              <span class="app-brand-text demo menu-text fw-bolder ms-2">Sneat</span>
            </a>

            <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
              <i class="bx bx-chevron-left bx-sm align-middle"></i>
            </a>
          </div>

          <div class="menu-inner-shadow"></div>

          <ul class="menu-inner py-1">
            <!-- Dashboard -->
            <li class="menu-item active">
              <a href="{% url 'perfil:home' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Panel inicial</div>
              </a>
            </li>

         

















            <li class="menu-header small text-uppercase">
              <span class="menu-header-text">Exámenes</span>
            </li>
            <li class="menu-item">
              <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-layout"></i>
                <div data-i18n="Layouts">Tránsito</div>
              </a>

              <ul class="menu-sub">
                <li class="menu-item">
                  <a href="{% url 'examen:examenes' %}" class="menu-link">
                    <div data-i18n="Without menu">Exámenes</div>
                  </a>
                </li>
                <li class="menu-item">
                     <a href="{% url 'examen:examenes' %}" class="menu-link">
                    <div data-i18n="Without menu">Resultados</div>

                  </a>
                </li>
               
              </ul>
            </li>







            <li class="menu-header small text-uppercase">
              <span class="menu-header-text">Pagos</span>
            </li>
             <li class="menu-item">
              <a href="{% url 'perfil:planes' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-collection"></i>
                <div data-i18n="Basic">Planes</div>
              </a>
            </li>
            


              <li class="menu-header small text-uppercase">
                <span class="menu-header-text">Afiliado 
                	{% if not request.user.profile.affiliated %}
                    <i class="menu-icon tf-icons bx bx-lock"></i>
                  {% endif %}
                </span>
              </li>

          	{% if request.user.profile.affiliated %}

              <li class="menu-item">
                <a href="{% url 'affiliate:links' %}" class="menu-link">
                  <i class="menu-icon tf-icons bx bx-collection"></i>
                  <div data-i18n="Basic">Mi cuenta de afiliado</div>
                </a>
              </li>
            {% else %}
               <li class="menu-item">
                <form action="{% url 'perfil:solicitar-afiliado' %}" method="post">
                    {% csrf_token %}

                    <button type="submit" class="btn btn-primary" style="margin-left: 30px;"> Solicitar afiliado
                        <i class="menu-icon tf-icons bx bx-lock-open"></i>
                    </button>
                </form>
                   
              </li>
            {% endif %}



     
          </ul>
        </aside>

templates/parts/nav_bar.html
{% load static %}
<nav
            class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
            id="layout-navbar"
          >
            <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
              <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                <i class="bx bx-menu bx-sm"></i>
              </a>
            </div>

            <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
              <!-- Search -->
              <div class="navbar-nav align-items-center">
                <div class="nav-item d-flex align-items-center">
                  <i class="bx bx-search fs-4 lh-0"></i>
                  <input
                    type="text"
                    class="form-control border-0 shadow-none"
                    placeholder="Search..."
                    aria-label="Search..."
                  />
                </div>
              </div>
              <!-- /Search -->

              <ul class="navbar-nav flex-row align-items-center ms-auto">
                <!-- Place this tag where you want the button to render. -->
                <li class="nav-item lh-1 me-3">
                  {% comment %} <a
                    class="github-button"
                    href="https://github.com/themeselection/sneat-html-admin-template-free"
                    data-icon="octicon-star"
                    data-size="large"
                    data-show-count="true"
                    aria-label="Star themeselection/sneat-html-admin-template-free on GitHub"
                    >Star</a
                  > {% endcomment %}
                  {% comment %} AQUI VA LA INFORMACION DEL CREDITO CUNATO TIENE EL USUARIO {% endcomment %}
                </li>

                <!-- User -->
                <li class="nav-item navbar-dropdown dropdown-user dropdown">
                  <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online">
                    {% if request.user.profile.picture %}
                      <img src="{{request.user.profile.picture.url}}" alt class="w-px-40 h-auto rounded-circle" />
                    {% else %}
                      <img src="{% static '/assets/img/avatars/1.png' %}" alt class="w-px-40 h-auto rounded-circle" />
                    {% endif %}
                    </div>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item" href="{% url 'perfil:detalle-perfil' request.user.profile.pk %}">
                        <div class="d-flex">
                          <div class="flex-shrink-0 me-3">
                            <div class="avatar avatar-online">
                                {% if request.user.profile.picture %}
                                  <img src="{{request.user.profile.picture.url}}" alt class="w-px-40 h-auto rounded-circle" />
                                {% else %}
                                  <img src="{% static '/assets/img/avatars/1.png' %}" alt class="w-px-40 h-auto rounded-circle" />
                                {% endif %}                             
                            </div>
                          </div>
                          <div class="flex-grow-1">
                            <span class="fw-semibold d-block">
                            {% if not request.user.profile.first_name or request.user.profile.last_name %}
                              {{request.user.username }}
                            {% else %}
                              {{ request.user.profile.first_name }} {{ request.user.profile.last_name }}
                            {% endif %}
                            </span>
                            {% comment %} <small class="text-muted">Admin</small> {% endcomment %}
                          </div>
                        </div>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'perfil:detalle-perfil' request.user.profile.pk %}">
                        <i class="bx bx-user me-2"></i>
                        <span class="align-middle">Mi cuenta</span>
                      </a>
                    </li>
                    {% comment %} <li>
                      <a class="dropdown-item" href="#">
                        <i class="bx bx-cog me-2"></i>
                        <span class="align-middle">Settings</span>
                      </a>
                    </li> {% endcomment %}
                    <li>
                      <a class="dropdown-item" href="{% url 'perfil:editar-perfil' request.user.profile.pk %}">
                        <i class="bx bx-cog me-2"></i>
                        <span class="align-middle">Editar cuenta</span>
                      </a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{%url 'perfil:lista-pagos' request.user.profile.pk %}">
                        <span class="d-flex align-items-center align-middle">
                          <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
                          <span class="flex-grow-1 align-middle">Pagos</span>
                          <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">
                            {{request.user.profile.planpago_set.count }}
                          </span>
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="dropdown-divider"></div>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'account_logout' %}">
                        <i class="bx bx-power-off me-2"></i>
                        <span class="align-middle">Cerrar sesión</span>
                      </a>
                    </li>
                  </ul>
                </li>
                <!--/ User -->
              </ul>
            </div>
          </nav>